08_Django/Django_aula/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

# Blog/
# Django urls:
# https://docs.djangoproject.com/en/5.0/topics/http/urls/
urlpatterns = [
    path('', views.blog, name='home'),
    # path('post/', views.blog, name='blog'),
    path('<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo'),
]

08_Django/Django_aula/conhecendo_django/urls.py
from django.contrib import admin
from django.urls import path, include

'''# http://127.0.0.1:8000/
# http://127.0.0.1:8000
# http://127.0.0.1:8000/blog
# http://127.0.0.1:8000/blog/
# http://127.0.0.1:8000/blog/articles/
# http://127.0.0.1:8000/blog/articles/comments
# http://127.0.0.1:8000/blog/articles/categories
# http://127.0.0.1:8000/blog/articles/authors
# http://127.0.0.1:8000/blog/articles/anything'''

urlpatterns = [
    path('',include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

08_Django/Django_aula/blog/models.py
from django.db import models

# Create your models here.

08_Django/Django_aula/blog/views.py
from blog.data import posts
from django.shortcuts import render
from typing import Any
from django.http import HttpRequest, Http404

def blog(request):
    print('blog')

    context = {
        # 'text': 'Olá blog',
        'posts': posts
    }

    return render(
        request,
        'blog/index.html',
        context
    )

def post(request: HttpRequest, post_id: int):
    found_post: dict[str, Any] | None = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Exception(Http404)

    context = {
        # 'text': 'Olá blog',
        'post': found_post,
        'title': found_post['title'] + ' - ',
    }

    return render(
        request,
        'blog/post.html',
        context
    )

def exemplo(request):
    print('exemplo')

    context = {
        'text': 'Olá exemplo',
        'title': 'Essa é uma página de exemplo - ',
    }

    return render(
        request,
        'blog/exemplo.html',
        context
    )

08_Django/Django_aula/blog/templates/blog/exemplo.html
{% extends "global/base.html" %}

{% block texto %} {{ text }} {% endblock texto %}

08_Django/Django_aula/blog/templates/blog/index.html
{% extends "global/base.html" %}

{% block texto %} 
    {{ text }} 
{% endblock texto %}

{% block posts %} 
    {% for post in posts %}
        {% include 'global/partials/postblock.html' %}
    {% endfor %}
{% endblock posts %} 

08_Django/Django_aula/blog/templates/blog/post.html
{% extends "global/base.html" %}

{% block texto %} 
    {{ text }} 
{% endblock texto %}

{% block posts %} 
    <article class="post single-post">
        <header>
        <h1 class="post__title">
            <a href="{% url 'blog:post' post.id %}">
            {{ post.title }}
            </a>
        </h1>
        </header>
        <div class="post__body">{{ post.body }}</div>
    </article>
{% endblock posts %} 